### ISSUE TITLE
carcosa doesnt create .secrets repository

### ISSUE THREAD

**Issue by vocuzi** [seletskiy/carcosa#18]
I tried adding a new secret, .secrets is not being created.  Terminal just pauses infinitely. ~_~

**Comment by vocuzi** [comment]
OS : kali-rolling x64

**Comment by pepa65** [comment]
Same here:
go version go1.13.1 linux/amd64

**Comment by seletskiy** [comment]
@vocuzi @pepa65: Did you press `CTRL-D` at new line after entering secret? `carcosa` reads secret (maybe multiline) from `stdin`, so you need to send EOF into the stream (if you're entering secret directly in the terminal).

**Comment by vocuzi** [comment]
On pressing `CTRL-D` after entering `carcosa -An superpassword`

![Screenshot from 2020-07-14 14-48-20](https://user-images.githubusercontent.com/21104691/87408585-4c801f80-c5e1-11ea-98c6-f275309a4fe9.png)

**Comment by seletskiy** [comment]
@vocuzi: Currently, `carcosa` requires existing repository (it's stated in the README: https://github.com/seletskiy/carcosa#using-new-repo), so you need to run `git init` if you use new repository.

**Comment by pepa65** [comment]
I did:
```
mkdir carcosa
cd carcosa
git init
carcosa -An token1
And this is the first secret; a prompt would have been very helpful for the uninitiated,
and even as feedback that it is working as it should for the adept.
^D
Enter master password: <master password>
```
Output:
```
2020-07-14 21:47:36.274 FATAL unable to open git repository "/home/pp/.secrets"
                              └─ repository does not exist
```
How do you set up a password and a repo??

**Comment by seletskiy** [comment]
@pepa65 Well, by default `carcosa` expects repository in `$HOME/.secrets` (as can be seen in the error message). It's a bit of legacy behavior that was left unchanged.

If you would like to use a custom repository path, you need to specify the `-p` flag with the path to the repository.
In your example you can call `carcosa` like this:

```
carcosa -An token1 -p .
```

`-p .` specifies to use a current working directory as a repository.

I agree with you that `carcosa` probably should be more verbose about what it expects.

**Comment by vocuzi** [comment]
@seletskiy thanks, that got it working. The readme doc was a bit confusing as it dint mention that you had to create a git repository inside .secrets

**Comment by seletskiy** [comment]
Yep, I agree that README needs to be updated.

**Comment by pepa65** [comment]
OK, all clear now!
