### ISSUE TITLE
Error when -L in empty repository

### ISSUE THREAD

**Issue by kovetskiy** [seletskiy/carcosa#4]
carcosa produces the error when trying to -L with empty repository:
```
└─ can't get tokens 
   └─ error executing git show-ref
      └─ exit status 1
```

how to reproduce:
```
mkdir -p /tmp/carcosa
carcosa -p /tmp/carcosa -A test
carcosa -p /tmp/carcosa -R test
carcosa -p /tmp/carcosa -L
```

This is low priority issue but it is a little big ambigious error message.

**Comment by seletskiy** [comment]
After rework, attempt to run `carcosa -p /tmp/carcosa -A test` on non-git repo directory now cause following error:
```
2019-10-25 14:38:06.187 FATAL unable to open git repository "/tmp/carcosa"
                              └─ repository does not exist
```

Which I think is sane behavior, so closing issue.
